name: Deploy Flask App to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: ecs-cicd-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t ecs-cicd-demo .

      - name: Tag Docker Image
        run: |
          docker tag ecs-cicd-demo:latest \
          ${{ steps.login-ecr.outputs.registry }}/ecs-cicd-demo:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/ecs-cicd-demo:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service \
            --cluster snoopy-ecs-demo \
            --service ecs-cicd-task-service \
            --force-new-deployment
